// Forces the Android NDK to r27+ so that every native library compiled from
// source (expo-modules-core, react-native-reanimated, -screens, -svg,
// -gesture-handler, RN core, …) is linked with 16 KB ELF segment alignment.
//
// Why: Google Play requires apps targeting Android 15+ to support 16 KB memory
// page devices ("Recompile your app with 16 KB native library alignment").
// NDK r27 is the first LTS release that links with `max-page-size=16384` by
// default, which is exactly what produces 16 KB-aligned .so files.
//
// Why a custom plugin: expo-build-properties (SDK 52 / v0.13.x) does not expose
// an `ndkVersion` option, so we patch the generated root build.gradle directly
// during prebuild. android/ is gitignored and regenerated by EAS on every
// build, so this plugin — not the on-disk android/build.gradle — is the source
// of truth for the NDK version.
const { withProjectBuildGradle } = require('@expo/config-plugins');

// r27.1.12297006 — first NDK LTS that defaults to 16 KB alignment.
const NDK_VERSION = '27.1.12297006';

/**
 * @param {import('@expo/config-plugins').ExpoConfig} config
 * @returns {import('@expo/config-plugins').ExpoConfig}
 */
module.exports = function with16KbAlignment(config) {
  return withProjectBuildGradle(config, (cfg) => {
    // The Expo Android template ships a Groovy root build.gradle. Bail loudly
    // if that ever changes so the NDK bump can never silently no-op.
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        'with16KbAlignment: expected a Groovy android/build.gradle, got ' +
          cfg.modResults.language,
      );
    }

    let contents = cfg.modResults.contents;

    if (/ndkVersion\s*=\s*["'][^"']*["']/.test(contents)) {
      // Replace the ndkVersion already declared in buildscript.ext { … }.
      contents = contents.replace(
        /ndkVersion\s*=\s*["'][^"']*["']/,
        `ndkVersion = "${NDK_VERSION}"`,
      );
    } else {
      // Fallback: inject into the ext { } block if no ndkVersion is present.
      contents = contents.replace(
        /ext\s*\{/,
        `ext {\n        ndkVersion = "${NDK_VERSION}"`,
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });
};
