/**
 * withAppGroupBridge — Expo config plugin that wires the AppGroupBridge
 * native module into the host iOS target during prebuild.
 *
 * Why this exists: Sprint 19 introduced a small native module that lets
 * the JS bundle write to the App Group's UserDefaults suite (so the
 * SwiftUI widget extension can read it). With ios/ now gitignored and
 * regenerated by `expo prebuild` on every build, the AppGroupBridge
 * source files would otherwise vanish. This plugin copies them back in
 * and registers them with the SyncLink target.
 *
 * Source-of-truth files live in this folder:
 *   plugins/AppGroupBridge/AppGroupBridge.m
 *   plugins/AppGroupBridge/AppGroupBridge.swift
 *
 * Mod chain:
 *   1. withDangerousMod(ios) — copy source files into
 *      `${projectRoot}/ios/SyncLink/AppGroupBridge/` after prebuild has
 *      written the rest of the project.
 *   2. withXcodeProject — create the AppGroupBridge group, add file
 *      references, attach them to the SyncLink target's Sources build
 *      phase. Idempotent: re-running the plugin won't duplicate entries.
 *
 * Sprint 19 TASK-1900 / EAS automation work.
 */

const { withDangerousMod, withXcodeProject } = require('@expo/config-plugins');
const fs   = require('fs');
const path = require('path');

const SOURCE_DIR_NAME    = 'AppGroupBridge';
const SOURCE_FILES       = ['AppGroupBridge.m', 'AppGroupBridge.swift'];
const HOST_TARGET_NAME   = 'SyncLink';

/**
 * Copy plugin-bundled bridge sources into ios/<HOST_TARGET>/AppGroupBridge/
 * so the Xcode mod below can reference them.
 */
function withCopyBridgeSources(config) {
  return withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const srcDir = path.join(__dirname, SOURCE_DIR_NAME);
      const dstDir = path.join(
        cfg.modRequest.platformProjectRoot,
        HOST_TARGET_NAME,
        SOURCE_DIR_NAME,
      );
      fs.mkdirSync(dstDir, { recursive: true });
      for (const file of SOURCE_FILES) {
        const from = path.join(srcDir, file);
        const to   = path.join(dstDir, file);
        if (fs.existsSync(from)) fs.copyFileSync(from, to);
      }
      return cfg;
    },
  ]);
}

/**
 * Add AppGroupBridge.{m,swift} to the SyncLink target's Sources build
 * phase. Skips when the files are already part of the project so the
 * plugin is safe to run on existing prebuilt projects too.
 */
function withRegisterBridgeInProject(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;

    const target = project.pbxTargetByName(HOST_TARGET_NAME);
    if (!target) {
      // Target not yet present (very early prebuild) — bail without error.
      return cfg;
    }

    // Find or create a PBXGroup for AppGroupBridge under the host target's
    // main group so the files appear in the Project navigator.
    const mainGroup = project.getFirstProject().firstProject.mainGroup;
    const hostGroupKey = findChildGroup(project, mainGroup, HOST_TARGET_NAME);
    if (!hostGroupKey) return cfg;

    let bridgeGroupKey = findChildGroup(project, hostGroupKey, SOURCE_DIR_NAME);
    if (!bridgeGroupKey) {
      const created = project.addPbxGroup(
        [],
        SOURCE_DIR_NAME,
        SOURCE_DIR_NAME,
        '"<group>"',
      );
      bridgeGroupKey = created.uuid;
      // Attach to the host group so it shows up in the navigator.
      project.addToPbxGroup(bridgeGroupKey, hostGroupKey);
    }

    for (const fileName of SOURCE_FILES) {
      const relPath = `${HOST_TARGET_NAME}/${SOURCE_DIR_NAME}/${fileName}`;
      if (isFileAlreadyInTarget(project, target.uuid, fileName)) continue;
      project.addSourceFile(
        relPath,
        { target: target.uuid },
        bridgeGroupKey,
      );
    }

    return cfg;
  });
}

function findChildGroup(project, parentKey, groupName) {
  const groups = project.hash.project.objects.PBXGroup ?? {};
  const parent = groups[parentKey];
  if (!parent || !parent.children) return null;
  for (const child of parent.children) {
    const childGroup = groups[child.value];
    if (childGroup && (childGroup.path === groupName || childGroup.name === groupName)) {
      return child.value;
    }
  }
  return null;
}

function isFileAlreadyInTarget(project, targetKey, fileName) {
  const buildPhases = project.hash.project.objects.PBXSourcesBuildPhase ?? {};
  const fileRefs   = project.hash.project.objects.PBXBuildFile ?? {};
  for (const key of Object.keys(buildPhases)) {
    if (key.endsWith('_comment')) continue;
    const phase = buildPhases[key];
    if (!phase?.files) continue;
    for (const f of phase.files) {
      if (typeof f.comment === 'string' && f.comment.includes(fileName)) return true;
      const ref = fileRefs[f.value];
      if (ref && typeof ref.fileRef_comment === 'string' && ref.fileRef_comment.includes(fileName)) {
        return true;
      }
    }
  }
  return false;
}

module.exports = function withAppGroupBridge(config) {
  config = withCopyBridgeSources(config);
  config = withRegisterBridgeInProject(config);
  return config;
};
