/**
 * AI / NL Parser types.
 *
 * These types define the contract between the NL input pipeline and the rest
 * of the app. The local parser (nlParser.ts) and the AI Edge Function both
 * return NLParseResult.
 *
 * Cost tiers:
 *  - Tier 1: Pure local (0 API cost)
 *  - Tier 2: Claude Haiku (~0.25¢ per 1K input tokens)
 *  - Tier 3: Claude Sonnet (reserved for complex generation tasks)
 */

// ─── Confidence ───────────────────────────────────────────────────────────────

/**
 * Confidence level of a parse result.
 *
 * Business rule: only call AI when confidence is 'low'.
 * high   → local parser matched with high certainty → render preview immediately
 * medium → local parser matched but some ambiguity → render preview with warning
 * low    → local parser could not parse reliably → fallback to Claude Haiku
 */
export type Confidence = 'high' | 'medium' | 'low';

// ─── Parsed event fields ──────────────────────────────────────────────────────

/**
 * Individual parsed field with its confidence score.
 * Used to highlight uncertain fields in the EventPreviewCard UI.
 */
export interface ParsedField<T> {
  value: T;
  confidence: Confidence;
}

/**
 * Fully parsed event extracted from natural language input.
 * All fields are optional — the user fills in missing info before confirming.
 */
export interface ParsedEventFields {
  title?: ParsedField<string>;
  startAt?: ParsedField<Date>;
  endAt?: ParsedField<Date>;
  allDay?: ParsedField<boolean>;
  location?: ParsedField<string>;
  description?: ParsedField<string>;
  repeatType?: ParsedField<'none' | 'daily' | 'weekly' | 'monthly' | 'yearly'>;
}

// ─── Parse result ─────────────────────────────────────────────────────────────

/**
 * Result returned by the NL parser (both local and AI).
 *
 * @example
 * // High confidence — local parser succeeded
 * {
 *   parsed: { title: { value: '점심', confidence: 'high' }, ... },
 *   confidence: 'high',
 *   source: 'local',
 *   rawInput: '내일 오후 1시 점심 약속',
 *   processingMs: 3,
 * }
 *
 * @example
 * // Low confidence — AI fallback needed
 * {
 *   parsed: {},
 *   confidence: 'low',
 *   source: 'local',
 *   rawInput: '이번 달 말에 뭔가 있었는데',
 *   processingMs: 1,
 * }
 */
export interface NLParseResult {
  parsed: ParsedEventFields;
  /** Overall confidence of the entire result (min of individual field confidences). */
  confidence: Confidence;
  /** Where the parse happened. */
  source: 'local' | 'ai';
  /** Original user input text. */
  rawInput: string;
  /** Time taken for local parsing in milliseconds. AI results use null. */
  processingMs: number | null;
  /** Error message if parsing failed entirely. */
  error?: string;
  /**
   * Build-101 — Vision NL 이 이미지에서 일정 정보를 못 찾았을 때. 클라가
   * "다시 시도 또는 직접 입력" prompt 노출.
   */
  noEventFound?: boolean;
}

// ─── AI service types ─────────────────────────────────────────────────────────

/** Request sent to the parse-event Edge Function. */
export interface AiParseRequest {
  /** text-only 사용 시 필수, image 첨부 시 빈 문자열 허용. */
  text: string;
  /** Current datetime for relative date resolution (ISO-8601). */
  contextDatetime: string;
  /** User's locale for date/time formatting hints. */
  locale: string;
  /** 사진 첨부 NL 등록 — raw base64 (data URL prefix 없이). */
  imageBase64?: string;
  /** imageBase64 의 media type. 기본 'image/jpeg'. */
  imageMediaType?: 'image/jpeg' | 'image/png' | 'image/webp' | 'image/gif';
}

/** Response from the parse-event Edge Function. */
export interface AiParseResponse {
  result: NLParseResult;
  /** Number of tokens consumed by this request. */
  tokensUsed: number;
}

/** Daily AI usage tracking (stored in AsyncStorage). */
export interface AiUsageRecord {
  date: string;           // YYYY-MM-DD
  callCount: number;
  tokensUsed: number;
}

// ─── Smart reminder ───────────────────────────────────────────────────────────

/** Smart reminder message generated by AI for an event. */
export interface SmartReminderMessage {
  eventId: string;
  userId: string;
  title: string;
  body: string;
  scheduledFor: Date;
}
